name: Debug YAML and JSON Files

on:
  push:
    branches:
      - main

jobs:
  debug-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install jq and yq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
        chmod +x /usr/bin/yq

    - name: Check jq and yq Versions
      run: |
        jq --version
        yq --version

    - name: Confirm File Existence
      run: |
        if [ ! -f path/to/yourfile.yaml ]; then echo "YAML file not found"; exit 1; fi
        if [ ! -f path/to/yourfile.json ]; then echo "JSON file not found"; exit 1; fi

    - name: Print YAML File Content
      run: cat path/to/yourfile.yaml

    - name: Print JSON File Content
      run: cat path/to/yourfile.json

    - name: Test YAML Processing with yq
      run: yq '.' path/to/yourfile.yaml

    - name: Test JSON Processing with jq
      run: jq '.' path/to/yourfile.json

    - name: Debug YAML with yq
      run: |
        echo "Running yq command..."
        yq '.key // "default_value"' path/to/yourfile.yaml || echo "yq command failed"

    - name: Debug JSON with jq
      run: |
        echo "Running jq command..."
        jq '.key // "default_value"' path/to/yourfile.json || echo "jq command failed"
