name: Debug YAML and JSON Processing

on:
  push:
    branches:
      - main

jobs:
  debug-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install jq and yq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
        chmod +x /usr/bin/yq

    - name: Check jq and yq Versions
      run: |
        jq --version
        yq --version

    - name: View YAML File Content
      run: cat path/to/yourfile.yaml

    - name: View JSON File Content
      run: cat path/to/yourfile.json

    - name: Process YAML File with yq
      run: yq '.key // "default_value"' path/to/yourfile.yaml

    - name: Process JSON File with jq
      run: jq '.key // "default_value"' path/to/yourfile.json
